import "./globals.css";
import type { Metadata } from "next";
import { SessionProviderWrapper } from "./components/authenticationuser/SessionProviderWrapper";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
import QueryProvider from "./provider/reactQueryProvider/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Foodking",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head></head>
      <body>
        <QueryProvider>
          <SessionProviderWrapper>
            <Header />
            {children}
            <Footer />
          </SessionProviderWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
